zookeeper:
  hosts:
    zk1.prodfit.dkfk.clusters.thinkjitsu.me:
      ansible_host: 52.39.3.133


kafka_broker:
  hosts:
    kafkabroker1.prodfit.dkfk.clusters.thinkjitsu.me:
      ansible_host: 52.39.3.133
      broker_id: 0
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: aws 
    kafkabroker2.prodfit.dkfk.clusters.thinkjitsu.me:
      ansible_host: 34.215.136.78
      broker_id: 1
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: aws 
    kafkabroker3.prodfit.dkfk.clusters.thinkjitsu.me:
      ansible_host: 52.38.169.90
      broker_id: 2
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: aws 

    kafkabroker4.prodfit.dkfk.clusters.thinkjitsu.me: 
      ansible_host: 35.247.68.28
      broker_id: 3
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: gcp 
    kafkabroker5.prodfit.dkfk.clusters.thinkjitsu.me: 
      ansible_host: 34.82.43.100
      broker_id: 4
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: gcp 
    kafkabroker6.prodfit.dkfk.clusters.thinkjitsu.me: 
      ansible_host: 35.247.117.227
      broker_id: 5
      kafka_broker_custom_properties:
        zookeeper.connect: zk1.prodfit.dkfk.clusters.thinkjitsu.me:2181
        broker.rack: gcp 
# schema_registry:
#   hosts:
#     ip-172-16-0-173.us-west-2.compute.internal:
#       ansible_host: ec2-54-191-167-172.us-west-2.compute.amazonaws.com

# kafka_rest:
#   hosts:
#     ip-172-16-0-173.us-west-2.compute.internal:
#       ansible_host: ec2-54-191-167-172.us-west-2.compute.amazonaws.com

# ksql:
#   hosts:
#     ip-172-16-0-173.us-west-2.compute.internal:
#       ansible_host: ec2-54-191-167-172.us-west-2.compute.amazonaws.com

# kafka_connect:
#   hosts:
#     ip-172-16-0-173.us-west-2.compute.internal:
#       ansible_host: ec2-54-191-167-172.us-west-2.compute.amazonaws.com

# control_center:
#   hosts:
#     ip-172-16-0-173.us-west-2.compute.internal:
#       ansible_host: ec2-54-191-167-172.us-west-2.compute.amazonaws.com

all:
  vars:
    ssl_enabled: false
    self_signed: false
    zookeeper_ssl_enabled: false
    secret_protection_enabled: false
    # proxy_env:
    #   http_proxy: http://localhost:8080
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/akochnev/.ssh/mv-vm-ssh-key.pem
    ansible_become: true
    installation_method: archive
    confluent_archive_file_source: http://packages.confluent.io/archive/6.1/confluent-6.1.0.tar.gz
    jmxexporter_enabled: true
    # confluent_server_enabled: false
    kafka_broker_schema_validation_enabled: true
    kafka_broker_custom_listeners:
      broker:
        name: BROKER
        port: 9091
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain
      client_listener:
        name: CLIENT
        port: 9093
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain